### PR TITLE
Create Todo_ReadMe

### PR DESCRIPTION
**Pull request by datasprings**
Updated areas of changes that could be used for intraday trading... accessing the decision of long/short/flat via API Request and integration with Alpaca api for paper trading account.

### CODE REVIEW

**Comment by datasprings** [comment]
Hello Junyoung! Wanted to chat with you about the current code base when you have a minute.  Can you email me at cnash@datasprings.com or text me/whatsapp at 720-481-8485. I have an update I wanted to post that I think could be useful... The initial code that is finished is passing parameter into main function to determine if its for intraday or daily url from https://financialmodelingprep.com/... I have this working, but wanted to also discuss your thoughts on if the model should be change or fit more for intraday data. Next steps I have on my list are to code integration with alpaca. 

Hope to talk soon! 

-Chad

**Comment by junyoung-sim** [comment]
Thank you for your kind interest. I do not plan on making significant additions to this repository as it was created and is being preserved for experimental and research purposes. You are still welcome to modify it based on your interests at your own risk as it has been my intention to allow open-source access. As you experiment with the model, I would be happy to answer any questions you may have about the technicalities of the trading model. Thank you, and have a great summer.

**Comment by datasprings** [comment]
Hello! My only questions at the moment.

1. I am used to using TensorFlow and other tools but new to how models work with C++. Is the model file already created seperate? Or is it trained / created using the existing code here? Wondering if we need to fit it or train it again for use with intraday data.

2.  When you run test, build, and run… is it needed to always run test and build for each instrument? Or if I wanted to change this to using a web api could I just call run?


Thanks!

Chad
***@***.***


Sent from my iPhone

On Jul 18, 2023, at 2:53 AM, Junyoung Sim ***@***.***> wrote:

﻿

Closed #2<https://github.com/junyoung-sim/quant/pull/2>.

**Comment by junyoung-sim** [comment]
1. The model trained using the existing code and parameters specified in the research paper is stored as ./models/checkpoint. It is a raw text file with 7MB of weights and biases of the agent network in the trading model (not the best way, but easy to implement and quick for debugging). You may try using the existing checkpoint on intraday data, but I don't have any data to tell you whether the existing model trained on daily data could be generalized to intraday data.

2. After compiling the code with `make`, you may use the following command line format for all three modes (build, test, run): `./exec mode ticker_list_separated_by_space ./models/checkpoint`. There must be at least one valid ticker preceding the checkpoint path starting with ./models. Please note that some types of securities like cryptocurrencies, futures, and options data may not be downloaded in this version. If you hope to experiment with such securities, you may take a look at `./python/download.py` and add snippets of code to access those data by referring to https://site.financialmodelingprep.com/developer/docs/dashboard/.

Thank you for your interest, and apologies for the late reply (I am currently overseas).

**Pull request closed without merging**
